### ISSUE TITLE
Transitions do not work on Chrome and Safari

### ISSUE THREAD

**Issue by tomitrescak** [Semantic-Org/Semantic-UI-Meteor#12]
Hi! thanks for this great package!

Recently I changed from semantic:ui-css to your semantic:ui package.
An immediate change was that all transitions stopped working on safari and chrome (they work in Firefox) and I am receiving:

```
Transition: There is no css animation matching the one you specified. scale in 
```

May it be related to jquery? I am running the 1.11 version.

Any help is greatly appreciated.

**Comment by tomitrescak** [comment]
Actually, not even dropdown worked in safari. Not sure why. I have deleted all files and had semantic-ui regenerate all less files and no change. Switching back to semantic:ui-css brought back the functionality.

**Comment by flemay** [comment]
You're welcome! :)

Have you installed `flemay:less-autoprefixer` package?

**Comment by jlukic** [comment]
This sounds like what would happen when the LESS files were parsed without autoprefixer, since most transitions require vendor prefixes.

**Comment by caprica** [comment]
I got tripped up by this, everything was working on OSX, Linux and Nexus5, but it didn't work on Nexus10 due to a missing CSS transition - an older browser version I guess on the Nexus10.

Removing the official LESS package and adding the less-autoprefixer one as suggested above fixed the problem for me.
