### ISSUE TITLE
checkbox can't initial correctly.

### ISSUE THREAD

**Issue by carrot93** [Semantic-Org/Semantic-UI-Meteor#16]
main.html

```
{{#each posts}}
<div class="ui checkbox">
  <input name="c1box" type="checkbox"><label></label>
</div>
{{/each}}
```

main.coffee

```
Template.main.events
  "click .checkbox":->
# this is the temp solution, for more 1 click first.
      $('.checkbox').checkbox()

Template.main.rendered = () ->
# this line is no effect,the checkboxes are still disabled before more 1 click first to active checkbox...
  $('.checkbox').checkbox()
```

How to next?

**Comment by joryphillips** [comment]
It looks like your Coffeescript is returning the object $('.checkbox').checkbox() and it shouldn't do that. I don't use coffeescript but the Js2.coffee translator says you should be putting a return statement at the end:  
  
```javascript
Template.main.rendered = () ->
  $('.checkbox').checkbox()
  return
```

**Comment by splendido** [comment]
Hello @carrot93,
I think the problem is a bit more general...
Everytime you have an `{{#if}}` or `{{#each}}` of whatever conditional, the HTML elements included therein are not granted to be already in place whn you get the `rendered` callback triggered.
This is especially true for an `if` clause which could change reactively during the life of the enclosing template...

The solution is to have something like this:

``` html
<template name='posts'>
{{#each posts}}
  {{> post}}
{{/each}}
</template>

<template name='post'>
  <div class="ui checkbox">
    <input name="c1box" type="checkbox"><label></label>
  </div>
</template>
```

and then

``` javascript
Template.post.onRendered(function(){
  this.$('.checkbox').checkbox()
});
```

this should be a general way to use any front-end framework which need elements initialization through JS code.

See also [this previous comment](https://github.com/Semantic-Org/Semantic-UI/issues/1618#issuecomment-72310597)

**Comment by splendido** [comment]
I think this should be written in the [README.md](https://github.com/Semantic-Org/Semantic-UI-Meteor/blob/master/README.md).
Feel free to create a PR to add a section about this.

CC @flemay

**Comment by joryphillips** [comment]
@splendido is right. deleting my earlier comment!
