### ISSUE TITLE
Problems with modals

### ISSUE THREAD

**Issue by ejosvp** [Semantic-Org/Semantic-UI-Meteor#27]
I don't know what is the best way of implement a `.modal`, but this is my code:

``` html
<template name="List">
    {{# if showModal}}
    <div class="ui modal new">
        ...
    </div>
    {{/ if}}
</template>
```

``` javascript
Template.List.onRendered(function () {
    Session.set("showModal", false);
});

Template.List.helpers({
    showModal: Session.get("showModal")
});

Template.List.events({
    "click .button.new": function () {
        Session.set("showModal", true);
        $('.ui.modal.new').modal({
            onHide: function () {
                Session.set("showModal", false);
            }
        }).modal('show');
    }
});
```

But `.modal` is moved to the end of the `body` tag, outside the `{{#if ...}`.

Any suggestions?

**Comment by jlukic** [comment]
Modals will detach themselves from DOM and position themselves as children of body. This is to reduce style recalculations caused by modal and dimmer animations (modals are notoriously bad performers) 

You can disable this behavior by specifying `detachable: false` in init 
http://semantic-ui.com/modules/modal.html#settings
