### ISSUE TITLE
Files not generated within Cloud9 IDE 

### ISSUE THREAD

**Issue by mrkvs** [Semantic-Org/Semantic-UI-Meteor#65]
Hi there!
I'm trying to install and use Semantic in Cloud9 environment but with no luck.
I started c9's Meteor workspace, installed all the dependencies, put **custom.semantic.json** in **/client/lib/semantic/**, run meteor. 
**custom.semantic.json** got filled in, but no file structure has been generated. Not a single file got generated.
Am I missing something?

**Comment by nooitaf** [comment]
Just tested in a free cloud9 thing. The free cloud9 tier was a little low on memory but it's possible. I even ran it with meteor 1.2.0.2, so a `meteor update` might help, as the default c9-meteor is 1.0.2 or such.. 

and Yes, you seem to have forgotten point 3 and 4 which are essential...  ;)
1. create an empty `custom.semantic.json` file somewhere in your project. 
2. start meteor
3. edit the file `custom.semantic.json` 
   - **it has to be different then the default one, otherwise meteor doesn't restart/refresh**
4. save the file and it will generate Semantic UI 
   - **if it still doesn't generate,.. remove `.custom.semantic.json` and meteor should restart/refresh and hopefulle generate the folders**

**Comment by mrkvs** [comment]
Thank you very much, this is exactly what I missed!

**Comment by nooitaf** [comment]
nice :)
