### ISSUE TITLE
Meteor refresh and build performance is severely impaired

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-Meteor#8]
After adding this package Meteor refresh process takes up to 10 times longer to refresh my app than without the package.
Meteor build process takes 3-4 times longer (my subjective feeling).
With 'semantic:ui-css' package none of this happens.
I'm running latest version of Meteor for Win.

**Comment by flemay** [comment]
Thank you for your feedback!

I don't know about Windows or any other people having this issue. For sure it will take more time (Although I didn't benchmark anything) due to the fact it needs to compile all less files and adds autoprefixer.

I would be curious if you replace `flemay:less-autoprefixer` with `less`. The ui will be broken but at least you can see if there is any performance issue.

**Comment by avalanche1** [comment]
Well, firstly, i've found out that mac build process is around 2 times faster than on win.
As for the issue itself: removing 'flemay:less-autoprefixer' alleviates the prob completely.
On mac if 'flemay:less-autoprefixer' is present, compilation is 3-4 times longer; still bearable though, considering mac overall speedy build process.
But on windows it becomes a real nuisance.

**Comment by avalanche1** [comment]
And why would you need to recompile .less files on client refresh anyway?
The changes are in the app code, not in SUI settings or smth.
Spinning this off to https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/9

**Comment by flemay** [comment]
If you did remove `flemay:less-autoprefixer` what did you use instead?

I would expect the same behaviour as the core `less` package on client refresh.

**Comment by avalanche1** [comment]
I used nothing = the ui was broken.
Just tested with core `less` package - it exhibits same drastic slowdown.
If your autoprefixer is based on core `less` - than the issue is with it.
But why would it recompile all .less files to .css if they didn't change? (ie, when I'm changing HTML)

**Comment by flemay** [comment]
I am not surprised.

I believe that your issues are not `semantic:ui` related but Meteor itself.

Every time a refresh occurs, the client looses all assets. Meteor re-pushes all assets (JS/CSS/Images/Fonts etc) to the client. I would not think Meteor caches the compiled result of any assets (Coffeescript, less).

Or maybe I am wrong?

**Comment by avalanche1** [comment]
Well, of course, it re-pushes assets to the client - that's natural.
But it seems Meteor also re-compiles source files, which is really unnecessary if the source hasn't been changed.
I'll address this to MDG

**Comment by avalanche1** [comment]
I guess we'll have to wait for all of those to be resolved..
https://github.com/meteor/meteor/labels/Project%3AIsobuild%3APerformance

**Comment by joryphillips** [comment]
Do either of you have a recommendation on how to speed up rebuilds in lieu of Meteor fixing this?

**Comment by avalanche1** [comment]
@joryphillips, I would advise to use `semantic:ui-css` for the time being.
No theming, alas... but for css customization I use custom overrides with `!important`declaration

**Comment by flemay** [comment]
@joryphillips I would focus on the UI and when I am happy I would compile it and remove the package.

**Comment by flemay** [comment]
Also a comment from Slava

> We are aware of this problem and working on the improvements. In the meanwhile, I must mention that packages get better caching as of today. So if you split up your app into packages, the rebuild time should be much better.

I haven't tested but **maybe** making a local package that contains `custom.semantic.json` might help.

**Comment by joryphillips** [comment]
Thank you both!

**Comment by flemay** [comment]
@avalanche1 @joryphillips Hey guys, I have updated `semantic:ui` to version 1.12.1_1 which would improve compilation time (see [this issue](https://github.com/Semantic-Org/Semantic-UI-Meteor/issues/11) and was wondering if you would like to give it a go? :)

Thanks!

**Comment by avalanche1** [comment]
Hey, Frederic!
Just tested: build time is still circa 3 times slower and refresh time circa 5 times slower than `semantic:ui-css`.
Still not usable for me(

**Comment by flemay** [comment]
Humm.. In the previous version Meteor was compiling all files in definitions because they ended with `.less`. I changed them to be `.import.less` so I am pretty sure it should be _faster_ but didn't benchmark it. At least you should see `.import.less` files in the folder `definitions`. :)

**Comment by avalanche1** [comment]
Ooops, my bad. I was using old `.less` files for testing.
Here are benchmark results with `.import.less` (for my proj):
- 9 seconds for refresh and rebuild each.  
  For `semantic:ui-css`:
- 4s refresh
- 5s rebuild

I'd say, a 2 times improvement over the previous version. Well done)

**Comment by joryphillips** [comment]
I was getting 13s rebuilds with the old version, and still 13s with the new. I deleted my prior semantic-ui folder and let the new version recreate everything... what am I doing wrong?

**Comment by avalanche1** [comment]
...mmm test in a blank project, like leaderboards

**Comment by joryphillips** [comment]
I forgot to delete the semantic-ui folder PRIOR to updating to the most recent version... dropped from 13s to 9s rebuilds. Better!  (I get 4s refreshes and 6s rebuilds with semantic:ui-css.)

**Comment by flemay** [comment]
For sure it will not get _faster_ than semantic:ui-css since the latter does not have any less files to compile.

Thank you guys for testing/benchmarking! :)

**Comment by tvld** [comment]
The problem is still persistent with 2.1.4_5. A new, "Welcome Meteor" app gets a build time of about 16 seconds (Ubuntu i7-4770K, 16GB, SSD's). I suppose we would need to move all the .less files to one package where Meteor wont notice on build, and compile all to one .css and let Meteor hanndle that one?  This makes Semantic-UI useless on Meteor....

**Comment by tvld** [comment]
Just tested with `less` package instead `flemay:less-autoprefixer`. The core less is 2x faster, about 8 seconds. Why we need autoprefixer?

**Comment by flemay** [comment]
@tvld I need to update `flemay:less-autoprefixer`. `less` package uses caching which is new since 1.2.

**Comment by avalanche1** [comment]
This may make things faster, but upgrading to 1.2 will slow your rebuilds by itself - https://github.com/meteor/meteor/issues/5269

**Comment by avalanche1** [comment]
And maybe this issue should be reopened for now?

**Comment by IstoraMandiri** [comment]
This is a bit of a pain point for me at the moment. I have a good spec machine but still getting slow rebuilds. Anything I can do?

**Comment by avalanche1** [comment]
You can remove the package and simply put raw semantic.js and semantic.css files into `client\compatibility` folder, just like I did :smiley:

**Comment by THPubs** [comment]
@avalanche1 Thanks I think I also might have to do that because even with the latest meteor, the build time is very slow with the semantic package. I'm using Linux.

**Comment by THPubs** [comment]
Just made some experiments...

Without the semantic-ui package, the build time is nearly 2,000 ms. With the package it's nearly 6,500 ms! If we remove the package and add the raw semantic-ui css (with less components), the build time is 3,500 ms. That's also a bit high. I have a project with bootstrap with even more packages and it goes only upto 2,500 ms! :smiley:

**Comment by jlukic** [comment]
I have been using a hacked version of this package that I've forgotten how terrible the packages performance is. Pinging @veered lets speed this jank up

**Comment by veered** [comment]
I think I know how to get rid of almost all of the additional build time, I'll take a look at it soon.

**Comment by pagesrichie** [comment]
@veered did you find a solution to speed up the build time?

**Comment by veered** [comment]
At Qualia, we made a package `qualia:semantic` and copied the SUI source into there. Packages rebuild independently of each other, so this helps build time a lot. The `package.js` for `qualia:semantic` ends up looking like this https://gist.github.com/veered/87c8a93be7555671eba9731122904c4d

We also forked the meteor CSS compiler package to not merge the CSS files in dev mode, as this takes is really slow if you have a lot of CSS. I opened a PR but it never got merged https://github.com/meteor/meteor/pull/5875

**Comment by pagesrichie** [comment]
@veered I dont know how to set this up.  I could not find a package "qualia:semantic" and I clicked on y our gist but I could not get it working.  Left a comment on the gist.  How would I get this set up?  And what load times are you getting with this?

**Comment by veered** [comment]
`qualia:semantic` is not a publicly available package. The approach I was suggesting involves creating a custom package `yourcompany:semantic` and putting it in the `packages/` directory of you project. This package would contain all of the less files for semantic. This is helpful because Meteor separates rebuilds by package. Right now any change to any file outside of a package in your project will recompile all of the less files. This is causing the poor performance.

The gist I posted is an example of what the `package.js` for `yourcompany:semantic` could look like.

If you don't need to customize the SUI less for your project you should just use https://atmospherejs.com/semantic/ui-css. It will be much much faster and not require any fancy shenanigans. It'll just work.

Also it's possible that this PR https://github.com/meteor/meteor/pull/9983 will just fix all of these issues across the board, without any user intervention required.

**Comment by pagesrichie** [comment]
I hope they fix it.. I tried your approach, line for line copied it, and even tracked it with the Profiler... the "other less plugin" still shows up taking 7-8 seconds during the reloading process, and for some reason after each refresh in even changing a line of code in meteor unrelated to styling - your package will still take 7-8 seconds to reload.

I've got juliancwirko:postcss disabled and the meteor css compiler (standard-minifier-css) disabled too for development.  When either of them are enabled, reloads take 11-12 seconds.  I'm sure the link you posted here: https://github.com/meteor/meteor/pull/5875 must be outdated .. before even worrying about minifying css I'm just trying to get basic reloading with semantic ui less working in a normal reload time.  Even if I'm not editing css and just changing one word in a react component.. it takes 8-9 seconds and without semantic-ui its 2 seconds.. but I need semantic ui for my project.

@veered Is there any way to speed up your package/idea?  I'd prefer using the LESS theming stuff instead of just using ui-css and having to override every single little thing..

**Comment by veered** [comment]
The isolated package approach definitely would work, but it's a bit difficult to communicate over Github how it works.

If you want to use the vanilla SUI css approach, make sure that you've also deleted the LESS files from your app directory.

In the long term, I'm optimistic that meteor/meteor#9983 will automatically fix the issues.

**Comment by pagesrichie** [comment]
The isolated package approach was actually straight forward - here is what I did, correct me if I did any steps wrong:

1) Created a new folder called "packages" under the root folder of my app.

2) Created another folder inside of that, Named the folder semantic-ui.

    Then inside that folder, created a folder called "lib" under that and dragged all my semantic-ui related files/folders (definitions, sites, themes, json, less etc) inside the lib folder.

3)  Took your gist code, renamed it in Package.describe to "mrt:semantic-ui", and in the onUse function, had to comment a few things such as the assets line (my semantic ui files didnt have icons , or ttfs or so) and also had to comment out // api.addAssets(assets, ['client', 'server']);

    In essence, Here's my full package.js code: 
    https://gist.github.com/pagesrichie/0518902b69d69baf750ed205bfc75912

4) Added mrt:semantic-ui to .meteor/pacakages file which immediately prompted a reload of my app as it installs the package.. and viola, the css DID work - however every time I tried to make a change to either a less file in this new package itself, OR in the app code itself, everything else would compile quickly, but this package would still take the same 8-10 seconds it took before when semantic-ui files were in the client side.  Also I did remove my semantic-ui files from the client, right now it's only being used in this package.  

I've been viewing the meteor profiler on the terminal, and even though this is is separated out into it's own package, for some reason, when I simply change a line of code in my app unrelated to any css even, it still takes 8-10 seconds when it comes to this package, and I still see "other less plugin.. 8000ms" whereas everything else is done in 1-2 seconds.

@veered Did I miss anything?

**Comment by veered** [comment]
Did you remove the less code from your app directory? I believe the current SUI meteor package creates a bunch of less files in your app directory

**Comment by pagesrichie** [comment]
Yes, I actually removed the pre-existing less files from semantic-ui that I had under the /client directory.  

I also disabled/removed the official semantic-ui meteor package from my .meteor/packages file.  

The only less files it is reading is the ones I copied into the custom package I had just made.

This is what profiler says:

| Top leaves:
| other plugin less........................................7,363 ms (2)
| other bundler writeFile....................................111 ms (241)
| 
| (#5) Total: 8,544 ms (Rebuild App)

:'(

**Comment by pagesrichie** [comment]
I even disabled and removed the less package from .meteor/packages.  I think your code still tells it to use less somehow.. so I removed it form there there to see what happens.

I just made a change by adding a single word to my app, unrelated to my css.  For some reason, it goes through the entire custom package for 7-8 seconds still.  Check out the profiler output:

| Top leaves:
| 
| (#6) Total: 80 ms (ProjectContext prepareProjectForBuild)
| 
| (#7) Profiling: Rebuild App mrt:semant...  -
|                                            -
| Rebuild App...................................................8,975 ms (1)

**Comment by pagesrichie** [comment]
I also have juliancwirko:postcss and standard-minifier-css@1.4.1 disabled

**Comment by veered** [comment]
Do you have any less files anywhere in your source tree?

**Comment by pagesrichie** [comment]
Nope - de nada.  I just did a thorough search. Definitely dont have any other less files in my app except for the semantic ui ones I separated and put in this custom package.

**Comment by veered** [comment]
And if you disable the custom package the build time drops?

**Comment by pagesrichie** [comment]
Oh hell yeah!  It drops by 8 seconds!  Just disabled it and This is all it takes (1.8 seconds to rebuild app):

| Top leaves:
| other JsImage#write........................................423 ms (1)
| other ClientTarget#write...................................173 ms (2)
| other bundler writeFile....................................122 ms (235)
| other ServerTarget#write...................................104 ms (1)
| 
| (#32) Total: 1,796 ms (Rebuild App)
| 

But as expected, now none of the styles work.

**Comment by veered** [comment]
Ok what happens if you try adding the SUI vanilla CSS package `meteor add semantic:ui-css
`

**Comment by pagesrichie** [comment]
just tried the vanilla package. 

This is the error I get:

meteor add semantic:ui-css
 => Errors while adding packages:             
                                              
While checking for semantic:ui-css@2.2.4:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your
platform.

**Comment by veered** [comment]
Interesting. Assuming you're using Blaze, another workaround would be adding a `head.html` file to your `client/` folder with this code:

```
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.css">
</head>
```

You might need to leave out the jQuery line, depends on your app.

**Comment by pagesrichie** [comment]
So then there's no way right now then to get LESS compiled quickly till that promising PR is resolved?

**Comment by veered** [comment]
There is certainly a way to get it working with the custom package approach, but it's difficult for me to tell why it isn't working for you without access to your code.

**Comment by pagesrichie** [comment]
What's your email so I can add you to my repo with access to the code?

**Comment by pagesrichie** [comment]
@veered What's your email?  So that I may add you to the repo for access to the code.

**Comment by veered** [comment]
lucas at qualia.com

**Comment by pagesrichie** [comment]
@veered Sent you an invitation to the repo, and also emailing you.  The pacakages are there in the latest commits, you would just have to disable the semantic ui css and js from the main.html head tags in the app so that you can test out custom package or other approach.  Gave you write access so you can either git push as new commit (or probably better to create a new branch instead).  If you want to add METEOR_PROFILER=1 to the startup you can do to view the profile, by going to package.json and adding it to the "start: {}" object.

To install the code:
meteor npm install

To run the code:
meteor npm start  (don't do just "meteor" as meteor npm start passes it proper settings flags that it needs to run the code properly, you need to run "meteor npm start")

Thanks!! Looking forward to your solution and totally appreciate your input on all this.
