### ISSUE TITLE
SUI files regeneration event

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-Meteor#9]
Documentations says:
_Every time Meteor starts (or refreshes) it calls the package semantic:ui to generate Semantic UI_
So I'm wondering if this behaviour is really necessary. Wouldn't it be reasonable to regenerate SUI only on SUI folder change, instead of regenerating on **any file** change inside app folder?

**Comment by flemay** [comment]
Yes it is...however if you read the next line in the documentation 

> i.e: The package has a simple mechanism based on the difference of custom.semantic.json and .custom.semantic.json to avoid generating all the time the files and folders. 

Therefore the plugin will be called but will not generate anything.

Every time the meteor refresh occurs, the client looses all assets. For instance, semantic:ui will have to add fonts/icons/images to the client on every refresh otherwise nothing will show up..
